services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pass@123
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce_network

  backend:
    image: ecommerce-backend
    container_name: backend
    restart: always
    depends_on:
      - mysql8
    environment:
      DB_HOST: mysql8
      DB_USER: root
      DB_PASSWORD: Pass@123
      DB_NAME: ecommerce
    ports:
      - "3000:3000"
    networks:
      - ecommerce_network

  frontend:
    image: ecommerce-frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:3001"
    networks:
      - ecommerce_network

volumes:
  mysql_data:

networks:
  ecommerce_network:
    driver: bridge

