piVersion: v1

kind: Secret

metadata:

    name: mysql-secret

        namespace: ecommerce

        type: Opaque

        stringData:

            mysql-root-password: rootpass

                mysql-user: appuser

                    mysql-password: apppass

                        mysql-database: ecommerce


