apiVersion: v1
kind: Secret
metadata:
  name: ecom-backend-secret
  namespace: ecom
type: Opaque
stringData:
  DB_HOST: "mysql"
  DB_USER: "root"
  DB_PASSWORD: "Pass@123"
  DB_NAME: "ecommerce_db"

  # Placeholder values (safe for public GitHub repo)
  SUPPORT_EMAIL: "placeholder"
  SUPPORT_EMAIL_PASS: "placeholder"

  JIRA_EMAIL: "placeholder"
  JIRA_API_TOKEN: "placeholder"
  JIRA_PROJECT_KEY: "NES"
  JIRA_BASE_URL: "https://nadheerkv.atlassian.net"

